services:
  app:
    build: .
    container_name: ssec_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ssec_app:/var/lib/spring/data
  db: 
    image: postgres:15
    container_name: ssec_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
      - ssec_data:/var/lib/postgresql/data
volumes:
  ssec_app:
  ssec_data:
